name: Pylint

on: 
  push:
    paths: 
      - '**.py'
      - '**.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get install libssl-dev libcurl4-openssl-dev
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        pip install pylint
    - name: pylint
      run: |
        pylint pypackage.py --const-rgx='[a-z\_][a-z0-9\_]{2,30}$' --disable=line-too-long
